openapi: 3.0.0
info:
  title: User API
  description: This API provides endpoints for creating and managing users and publications.
  version: 1.0.0

paths:
  /publications/user:
    get:
      tags:
        - User
      summary: Get all publications for a user.
      description: This endpoint gets all publications for a specific user.
      security:
        - Bearer: []
      responses:
        200:
          description: The publications were found successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Publication'
        401:
          description: The user is not logged in.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Publication:
      type: object
      properties:
        id:
          type: integer
          description: The publication's ID.
          example: 1
        title:
          type: string
          description: The publication's title.
          example: My first publication.
        description:
          type: string
          description: The publication's description.
          example: This is my first publication.
        priority:
          type: integer
          description: The publication's priority.
          example: 1
        status:
          type: string
          description: The publication's status.
          example: Draft
    Error:
      type: object
      properties:
        message:
          type: string
          description: The error message.
          example: Invalid request body.
        status_code:
          type: integer
          description: The HTTP status code.
          example: 400
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
